### ISSUE TITLE
Conditionally load variables based on command/ story name

### ISSUE THREAD

**Issue by stephenstack** [laravel/envoy#162] opened 2019-09-16 11:47 UTC
Hi,

I would simply like a way to run variations of the @setup section based on the task type. For example if I run;
envoy run install - I can check for 'install' in the @setup section and load a set of variables, error checking and so on. This 'install' would require specific parameters.
If I run;
envoy run upgrade - I can check for the 'upgrade' command and load a separate set of setup vars, or tasks. Maybe some are shared with 'install'. 
After setup, their individual stories are run. 

Is this possible, can it be done easily? I've tried everything, But I cannot find a way to access these.

Thank you

**Comment by LorenzoSapora** [comment] 2019-09-18 10:44
Not the cleanest of options but you can pass variables to envoy like this

```bash
envoy run deploy --foo=install
```

And retrieve it in envoy

```php
@setup
    $foo = isset($foo) ? $foo : "Foo Empty";
@endsetup

@task
    echo {{ $foo }}
@endtask
```

You could create some if statements around that. Hope that helps.

**Comment by stephenstack** [comment] 2019-09-20 05:55
Thanks I had considered this. But my app will be redistributable, so I'd like the process to have as few params as possible. I will be adding other params. 

My suggestion above would be very clean and convenient.

**Comment by driesvints** [comment] 2019-09-23 11:10
Isn't this a duplicate of https://github.com/laravel/envoy/issues/149 ?

**Comment by driesvints** [comment] 2019-09-27 18:47
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Closed by driesvints** 2019-09-27 18:47 UTC
Labels: needs more info
